//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;


public class PokeballProjectileController : BaseProjectileController
{
		public void Reset ()
		{
				projectileAcceleration.x = -5;
				projectileAcceleration.y = -5;
		}
		public void Shoot ()
		{
				if (shootTimer <= 0) {
						currentAmmo--;
						shootTimer += 1 / rateOfFire;
						Spawnprojectile ();
					
				}
			
		}
		override public  void Spawnprojectile ()
		{
				for (int i = 0; i < projectileCount; i++) {
						GameObject newprojectile = (GameObject)Instantiate (projectile, transform.position, transform.rotation);
						newprojectile.name = "Defaultprojectile";
						//newprojectile.AddComponent<Rigidbody> ();
						newprojectile.rigidbody.mass = projectileMass;
						newprojectile.rigidbody.drag = 0;
						newprojectile.rigidbody.useGravity = false;
				
						newprojectile.rigidbody.velocity =
					Camera.main.transform.forward * (projectileSpeed + projectileSpeedDelta * (Random.value - 0.5f) * 2)
								+ Camera.main.transform.up * (verticalSpread * (Random.value - 0.5f) * 2)
								+ Camera.main.transform.right * (horizontalSpread * (Random.value - 0.5f) * 2);
				
						newprojectile.AddComponent<ConstantForce> ();
						newprojectile.constantForce.force = (projectileAcceleration.x * Camera.main.transform.forward
								+ projectileAcceleration.y * Camera.main.transform.up
								+ projectileAcceleration.z * Camera.main.transform.right) * accelerationScale;
						newprojectile.constantForce.force += (projectileGlobalAcceleration) * accelerationScale;
						newprojectile.constantForce.force *= 50f;
						audioSource = gameObject.AddComponent<AudioSource> ();
						audioSource.clip = shootSound;
						audioSource.Play ();
				
						//newprojectile.AddComponent<APEprojectile> ().life = projectileLife;
				}
		}
}


